# Generated by Django 5.2.7 on 2025-11-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
